---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlapp
  template:
    metadata:
      labels:
        app: mlapp
    spec:
      containers:
      - name: mlapp
        image: sidiali/app_repo:app_tag
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mlapp
spec:
  selector:
    app: mlapp
  ports: 
  - port: 80
    protocol: TCP
    targetPort: 80
    
